services:
  split_video_service:
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - ./:/app
      - ./data/database:/app/database
      - ./data/uploads:/app/uploads
    ports:
      - 8002:3000
      - 2345:2345

    cap_add:
      - SYS_PTRACE

    security_opt:
      - seccomp:unconfined
