services:
  split_video_service:
    build: .
    container_name: video_split_service
    restart: always
    env_file:
      - .env
    volumes:
      - ./data/database:/app/database
      - ./data/uploads:/app/uploads
      - ./data/logs:/app/logs
    networks:
      card:
        ipv4_address: 172.21.0.72

networks:
  card:
    name: card
    ipam:
      config:
        - subnet: 172.21.0.0/16
