package main

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"io"
	"io/fs"
	"os"
	"path"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/tdewolff/minify/v2"
	"github.com/tdewolff/minify/v2/css"
	"github.com/tdewolff/minify/v2/js"
)

const (
	sourceRoot = "public/static"
	outputRoot = "dist/static"
	manifest   = "assets/manifest_gen.go"
	hashLen    = 8
)

var (
	assetDirs  = []string{"css", "js"}
	jsImportRe = regexp.MustCompile(`(from\s+["']|import\s+["'])(\./[^"']+)(["'])`)
	jsMimeRe   = regexp.MustCompile(`^(application|text)/(x-)?(java|ecma)script$`)
)

type assetFile struct {
	srcPath     string
	logicalPath string
}

func main() {
	prod := false
	for _, arg := range os.Args[1:] {
		if arg == "prod" {
			prod = true
			break
		}
	}

	if err := run(prod); err != nil {
		fmt.Fprintf(os.Stderr, "assetbuild: %v\n", err)
		os.Exit(1)
	}
}

func run(prod bool) error {
	if !prod {
		if err := os.RemoveAll(outputRoot); err != nil {
			return fmt.Errorf("clean output: %w", err)
		}
		return resetManifest()
	}

	if err := os.RemoveAll(outputRoot); err != nil {
		return fmt.Errorf("clean output: %w", err)
	}

	var files []assetFile

	for _, dir := range assetDirs {
		srcDir := filepath.Join(sourceRoot, dir)
		matches, err := collectFiles(srcDir)
		if err != nil {
			return err
		}

		for _, srcPath := range matches {
			rel, err := filepath.Rel(sourceRoot, srcPath)
			if err != nil {
				return fmt.Errorf("rel path %s: %w", srcPath, err)
			}

			files = append(files, assetFile{
				srcPath:     srcPath,
				logicalPath: filepath.ToSlash(rel),
			})
		}
	}

	manifestEntries := make(map[string]string, len(files))
	if err := buildProdAssets(files, manifestEntries); err != nil {
		return err
	}

	if err := copySVGAssets(); err != nil {
		return err
	}

	return writeManifest(manifestEntries)
}

func resetManifest() error {
	content := "// Code generated by cmd/assetbuild. DO NOT EDIT.\npackage assets\n\nvar Manifest = map[string]string{}\n"
	if err := os.WriteFile(manifest, []byte(content), 0o644); err != nil {
		return fmt.Errorf("write manifest: %w", err)
	}
	return nil
}

func copySVGAssets() error {
	pattern := filepath.Join(sourceRoot, "*.svg")
	matches, err := filepath.Glob(pattern)
	if err != nil {
		return fmt.Errorf("glob svg: %w", err)
	}

	for _, srcPath := range matches {
		dstPath := filepath.Join(outputRoot, filepath.Base(srcPath))
		if err := copyFile(srcPath, dstPath); err != nil {
			return err
		}
	}

	return nil
}

func collectFiles(root string) ([]string, error) {
	var files []string
	err := filepath.WalkDir(root, func(p string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			return nil
		}
		files = append(files, p)
		return nil
	})
	if err != nil {
		return nil, fmt.Errorf("walk %s: %w", root, err)
	}
	return files, nil
}

func buildProdAssets(files []assetFile, manifest map[string]string) error {
	logicalSet := make(map[string]assetFile, len(files))
	for _, f := range files {
		logicalSet[f.logicalPath] = f
	}

	minifier := newMinifier()
	pending := append([]assetFile(nil), files...)

	for len(pending) > 0 {
		progress := false
		next := make([]assetFile, 0, len(pending))

		for _, f := range pending {
			content, err := os.ReadFile(f.srcPath)
			if err != nil {
				return fmt.Errorf("read %s: %w", f.srcPath, err)
			}

			if !jsImportsReady(f.logicalPath, content, logicalSet, manifest) {
				next = append(next, f)
				continue
			}

			content, err = processAsset(content, f.logicalPath, manifest, minifier)
			if err != nil {
				return err
			}

			hashedPath := hashContent(content, f.logicalPath)
			dstPath := filepath.Join(outputRoot, filepath.FromSlash(hashedPath))
			if err := writeFile(dstPath, content); err != nil {
				return err
			}

			manifest[f.logicalPath] = hashedPath
			progress = true
		}

		if !progress {
			return fmt.Errorf("unresolved js imports (possible circular dependency)")
		}
		pending = next
	}

	return nil
}

func newMinifier() *minify.M {
	m := minify.New()
	m.AddFunc("text/css", css.Minify)
	m.AddFuncRegexp(jsMimeRe, js.Minify)
	return m
}

func processAsset(content []byte, logicalPath string, manifest map[string]string, m *minify.M) ([]byte, error) {
	ext := strings.ToLower(filepath.Ext(logicalPath))
	switch ext {
	case ".js":
		content = rewriteJSImports(content, logicalPath, manifest)
		out, err := m.Bytes("application/javascript", content)
		if err != nil {
			return nil, fmt.Errorf("minify js %s: %w", logicalPath, err)
		}
		return out, nil
	case ".css":
		out, err := m.Bytes("text/css", content)
		if err != nil {
			return nil, fmt.Errorf("minify css %s: %w", logicalPath, err)
		}
		return out, nil
	default:
		return content, nil
	}
}

func hashContent(content []byte, logicalPath string) string {
	sum := sha256.Sum256(content)
	hash := hex.EncodeToString(sum[:])[:hashLen]

	base := filepath.Base(logicalPath)
	ext := filepath.Ext(base)
	name := strings.TrimSuffix(base, ext)
	hashedBase := fmt.Sprintf("%s.%s%s", name, hash, ext)
	return filepath.ToSlash(path.Join(path.Dir(logicalPath), hashedBase))
}

func jsImportsReady(logicalPath string, content []byte, logicalSet map[string]assetFile, manifest map[string]string) bool {
	if !strings.HasSuffix(strings.ToLower(logicalPath), ".js") {
		return true
	}

	for _, importPath := range extractJSImports(content) {
		target := resolveRelativeImport(logicalPath, importPath)
		if target == "" {
			continue
		}
		if _, ok := logicalSet[target]; !ok {
			continue
		}
		if _, ok := manifest[target]; !ok {
			return false
		}
	}
	return true
}

func extractJSImports(content []byte) []string {
	matches := jsImportRe.FindAllSubmatch(content, -1)
	imports := make([]string, 0, len(matches))
	for _, sub := range matches {
		if len(sub) >= 3 {
			imports = append(imports, string(sub[2]))
		}
	}
	return imports
}

func writeFile(dst string, content []byte) error {
	if err := os.MkdirAll(filepath.Dir(dst), 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", filepath.Dir(dst), err)
	}
	if err := os.WriteFile(dst, content, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", dst, err)
	}
	return nil
}

func rewriteJSImports(content []byte, logicalPath string, manifest map[string]string) []byte {
	return jsImportRe.ReplaceAllFunc(content, func(match []byte) []byte {
		sub := jsImportRe.FindSubmatch(match)
		if len(sub) < 4 {
			return match
		}

		importPath := string(sub[2])
		targetLogical := resolveRelativeImport(logicalPath, importPath)
		hashedTarget, ok := manifest[targetLogical]
		if !ok {
			return match
		}

		newImport := relativeImportPath(logicalPath, hashedTarget)
		return []byte(string(sub[1]) + newImport + string(sub[3]))
	})
}

func resolveRelativeImport(currentLogical, importPath string) string {
	if !strings.HasPrefix(importPath, "./") && !strings.HasPrefix(importPath, "../") {
		return ""
	}
	dir := path.Dir(currentLogical)
	return path.Clean(path.Join(dir, importPath))
}

func relativeImportPath(fromLogical, toHashed string) string {
	fromDir := filepath.FromSlash(path.Dir(fromLogical))
	toPath := filepath.FromSlash(toHashed)
	rel, err := filepath.Rel(fromDir, toPath)
	if err != nil {
		return "./" + path.Base(toHashed)
	}
	rel = filepath.ToSlash(rel)
	if !strings.HasPrefix(rel, ".") {
		rel = "./" + rel
	}
	return rel
}

func copyFile(src, dst string) error {
	if err := os.MkdirAll(filepath.Dir(dst), 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", filepath.Dir(dst), err)
	}

	in, err := os.Open(src)
	if err != nil {
		return fmt.Errorf("open %s: %w", src, err)
	}
	defer in.Close()

	out, err := os.Create(dst)
	if err != nil {
		return fmt.Errorf("create %s: %w", dst, err)
	}
	defer out.Close()

	if _, err := io.Copy(out, in); err != nil {
		return fmt.Errorf("copy %s -> %s: %w", src, dst, err)
	}

	return out.Close()
}

func writeManifest(entries map[string]string) error {
	keys := make([]string, 0, len(entries))
	for key := range entries {
		keys = append(keys, key)
	}
	sort.Strings(keys)

	var b strings.Builder
	b.WriteString("// Code generated by cmd/assetbuild. DO NOT EDIT.\n")
	b.WriteString("package assets\n\n")
	b.WriteString("\tvar Manifest = map[string]string{\n")
	for _, key := range keys {
		fmt.Fprintf(&b, "\t\t%q: %q,\n", key, entries[key])
	}
	b.WriteString("\t}\n")

	if err := os.MkdirAll(filepath.Dir(manifest), 0o755); err != nil {
		return fmt.Errorf("mkdir manifest dir: %w", err)
	}

	if err := os.WriteFile(manifest, []byte(b.String()), 0o644); err != nil {
		return fmt.Errorf("write manifest: %w", err)
	}

	return nil
}
