package main

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const (
	sourceRoot = "public/static"
	outputRoot = "dist/static"
	manifest   = "assets/manifest_gen.go"
	hashLen    = 8
)

var assetDirs = []string{"css", "js"}

func main() {
	prod := false
	for _, arg := range os.Args[1:] {
		if arg == "prod" {
			prod = true
			break
		}
	}

	if err := run(prod); err != nil {
		fmt.Fprintf(os.Stderr, "assetbuild: %v\n", err)
		os.Exit(1)
	}
}

func run(prod bool) error {
	if err := os.RemoveAll(outputRoot); err != nil {
		return fmt.Errorf("clean output: %w", err)
	}

	manifestEntries := make(map[string]string)

	for _, dir := range assetDirs {
		pattern := filepath.Join(sourceRoot, dir, "*")
		matches, err := filepath.Glob(pattern)
		if err != nil {
			return fmt.Errorf("glob %s: %w", pattern, err)
		}

		for _, srcPath := range matches {
			info, err := os.Stat(srcPath)
			if err != nil {
				return err
			}
			if info.IsDir() {
				continue
			}

			logicalPath, hashedName, err := hashAsset(srcPath, dir)
			if err != nil {
				return err
			}

			dstPath := filepath.Join(outputRoot, dir, hashedName)
			if err := copyFile(srcPath, dstPath); err != nil {
				return err
			}

			manifestEntries[logicalPath] = filepath.ToSlash(filepath.Join(dir, hashedName))
		}
	}

	if err := copySVGAssets(); err != nil {
		return err
	}

	if prod {
		return writeManifest(manifestEntries)
	}
	return nil
}

func copySVGAssets() error {
	pattern := filepath.Join(sourceRoot, "*.svg")
	matches, err := filepath.Glob(pattern)
	if err != nil {
		return fmt.Errorf("glob svg: %w", err)
	}

	for _, srcPath := range matches {
		dstPath := filepath.Join(outputRoot, filepath.Base(srcPath))
		if err := copyFile(srcPath, dstPath); err != nil {
			return err
		}
	}

	return nil
}

func hashAsset(srcPath, dir string) (logicalPath, hashedName string, err error) {
	content, err := os.ReadFile(srcPath)
	if err != nil {
		return "", "", fmt.Errorf("read %s: %w", srcPath, err)
	}

	sum := sha256.Sum256(content)
	hash := hex.EncodeToString(sum[:])[:hashLen]

	base := filepath.Base(srcPath)
	ext := filepath.Ext(base)
	name := strings.TrimSuffix(base, ext)
	hashedName = fmt.Sprintf("%s.%s%s", name, hash, ext)
	logicalPath = filepath.ToSlash(filepath.Join(dir, base))

	return logicalPath, hashedName, nil
}

func copyFile(src, dst string) error {
	if err := os.MkdirAll(filepath.Dir(dst), 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", filepath.Dir(dst), err)
	}

	in, err := os.Open(src)
	if err != nil {
		return fmt.Errorf("open %s: %w", src, err)
	}
	defer in.Close()

	out, err := os.Create(dst)
	if err != nil {
		return fmt.Errorf("create %s: %w", dst, err)
	}
	defer out.Close()

	if _, err := io.Copy(out, in); err != nil {
		return fmt.Errorf("copy %s -> %s: %w", src, dst, err)
	}

	return out.Close()
}

func writeManifest(entries map[string]string) error {
	keys := make([]string, 0, len(entries))
	for key := range entries {
		keys = append(keys, key)
	}
	sort.Strings(keys)

	var b strings.Builder
	b.WriteString("// Code generated by cmd/assetbuild. DO NOT EDIT.\n")
	b.WriteString("package assets\n\n")
	b.WriteString("\tvar Manifest = map[string]string{\n")
	for _, key := range keys {
		fmt.Fprintf(&b, "\t\t%q: %q,\n", key, entries[key])
	}
	b.WriteString("\t}\n")

	if err := os.MkdirAll(filepath.Dir(manifest), 0o755); err != nil {
		return fmt.Errorf("mkdir manifest dir: %w", err)
	}

	if err := os.WriteFile(manifest, []byte(b.String()), 0o644); err != nil {
		return fmt.Errorf("write manifest: %w", err)
	}

	return nil
}
